#!/usr/bin/env node
// Assemble a body file. The save skill owns summary judgment and publication.
import { existsSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { basename, isAbsolute, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

function webUrl(value) {
  const url = new URL(value);
  if (!['https:', 'http:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) {
    throw new Error('expected an HTTP(S) URL without credentials, query, or fragment');
  }
  return url.href.replace(/\/$/, '');
}

export function renderPrBody({ repoRoot = '.', changeRoot, mode, repoUrl, branch, summaryFile, previewUrl }) {
  if (!changeRoot || !summaryFile || !branch || !['active', 'archive'].includes(mode)) throw new Error('change root, mode, branch, and summary file are required');
  const root = resolve(repoRoot);
  const selected = resolve(root, changeRoot);
  const path = relative(root, selected).split(sep).join('/');
  if (!path || path === '..' || path.startsWith('../') || isAbsolute(path)) throw new Error('change must be inside the selected repository');
  const proposal = readFileSync(resolve(selected, 'proposal.md'), 'utf8');
  const status = proposal.match(/^\*\*Status:\*\*[ \t]*([^\r\n]*)/m)?.[1].trim();
  if (!status) throw new Error('proposal is missing Status');
  const tasks = readFileSync(resolve(selected, 'tasks.md'), 'utf8');
  const summary = readFileSync(summaryFile, 'utf8').trim();
  if (!summary || !tasks.trim()) throw new Error('summary and tasks must not be empty');
  const repo = webUrl(repoUrl);
  const preview = previewUrl ? webUrl(previewUrl) : null;
  const encodedPath = path.split('/').map(encodeURIComponent).join('/');
  const link = `${repo}/blob/${encodeURIComponent(branch)}/${encodedPath}`;
  const name = mode === 'archive' ? basename(selected).replace(/^\d{4}-\d{2}-\d{2}-/, '') : basename(selected);
  let body = `## Summary\n\n**Status:** ${status}\n\n${summary}\n\n## Tasks\n\n${tasks}`;
  if (!body.endsWith('\n')) body += '\n';
  if (existsSync(resolve(selected, 'review.html'))) {
    body += `\n## Review\n\n[Interactive review](${link}/review.html) — open from a clone to view and annotate offline; GitHub shows the source.\n`;
  }
  if (preview) body += `\n## Preview\n\n[${preview}](${preview})\n`;
  body += `\n---\n_Handoff: [${path}](${link})${mode === 'active' ? ` — resume with \`/continue ${name}\`` : ''}. This body is regenerated by every /save; comment rather than editing it._\n`;
  return body;
}

export function writePrBody(options, outputFile) {
  if (!outputFile) throw new Error('output file is required');
  const selected = resolve(options.repoRoot ?? '.', options.changeRoot ?? '.');
  const output = resolve(outputFile);
  const forbidden = ['proposal.md', 'tasks.md', 'review.html', 'review-visuals.html'].map(p => resolve(selected, p));
  if (forbidden.includes(output) || output === resolve(options.summaryFile ?? '.')) throw new Error('output must not replace an input artifact');
  const body = renderPrBody(options);
  if (existsSync(output) && readFileSync(output, 'utf8') === body) return false;
  const temporary = `${output}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;
  try { writeFileSync(temporary, body, { flag: 'wx' }); renameSync(temporary, output); }
  finally { rmSync(temporary, { force: true }); }
  return true;
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const options = {};
    const keys = { '--repo-root': 'repoRoot', '--change-root': 'changeRoot', '--mode': 'mode', '--repo-url': 'repoUrl', '--branch': 'branch', '--summary-file': 'summaryFile', '--preview-url': 'previewUrl', '--output': 'output' };
    const args = process.argv.slice(2);
    for (let i = 0; i < args.length; i += 2) {
      if (!keys[args[i]] || !args[i + 1]) throw new Error('invalid option or missing value');
      options[keys[args[i]]] = args[i + 1];
    }
    console.log(`PR body: ${writePrBody(options, options.output) ? 'updated' : 'unchanged'}`);
  } catch (error) { console.error(`PR body: ${error.message}`); process.exitCode = 1; }
}
